"""empty message

Revision ID: 1f76995dfa35
Revises: 5145276cfdbd
Create Date: 2022-04-11 11:35:33.008514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f76995dfa35'
down_revision = '5145276cfdbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookouts', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.drop_constraint('cookouts_creator_fkey', 'cookouts', type_='foreignkey')
    op.create_foreign_key(None, 'cookouts', 'users', ['creator_id'], ['id'])
    op.drop_column('cookouts', 'creator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookouts', sa.Column('creator', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cookouts', type_='foreignkey')
    op.create_foreign_key('cookouts_creator_fkey', 'cookouts', 'users', ['creator'], ['id'])
    op.drop_column('cookouts', 'creator_id')
    # ### end Alembic commands ###
