"""empty message

Revision ID: 4d4d13ea3022
Revises: 071f151a4e46
Create Date: 2022-04-10 11:27:29.381196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d4d13ea3022'
down_revision = '071f151a4e46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookouts', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cookouts', 'description')
    # ### end Alembic commands ###
