"""empty message

Revision ID: 5145276cfdbd
Revises: 4d4d13ea3022
Create Date: 2022-04-11 11:25:37.288858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5145276cfdbd'
down_revision = '4d4d13ea3022'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cookouts_attendees_fkey', 'cookouts', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('cookouts_attendees_fkey', 'cookouts', 'users', ['attendees'], ['id'])
    # ### end Alembic commands ###
