"""empty message

Revision ID: 6d9c81e74a14
Revises: 1f76995dfa35
Create Date: 2022-04-12 11:02:44.696834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d9c81e74a14'
down_revision = '1f76995dfa35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cookouts', 'attendees')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookouts', sa.Column('attendees', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
