"""empty message

Revision ID: ddbca57d551b
Revises: 2ba80eaae8a9
Create Date: 2022-04-13 09:46:54.360376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ddbca57d551b'
down_revision = '2ba80eaae8a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drinks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['cookouts.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('foods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['cookouts.id'], ),
    sa.ForeignKeyConstraint(['provider_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('cookouts', 'drink')
    op.drop_column('cookouts', 'food')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cookouts', sa.Column('food', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('cookouts', sa.Column('drink', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('foods')
    op.drop_table('drinks')
    # ### end Alembic commands ###
