"""empty message

Revision ID: edfed64e2720
Revises: ddbca57d551b
Create Date: 2022-04-13 13:04:23.446706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edfed64e2720'
down_revision = 'ddbca57d551b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cookouts', 'attendees')
    op.add_column('users', sa.Column('cookouts_att', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'cookouts', ['cookouts_att'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'cookouts_att')
    op.add_column('cookouts', sa.Column('attendees', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
